# Generated by Django 3.0.5 on 2020-04-25 20:19

from django.db import migrations, models
import image.models


class Migration(migrations.Migration):

    dependencies = [
        ("image", "0002_auto_20200425_1501"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(upload_to=image.models.user_directory_path),
        ),
    ]
